# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn clean package -DskipTests --file pom.xml
      # Building jar: /home/runner/work/keycloak-organization-assigner/keycloak-organization-assigner/target/keycloak-auto-org-assigner-1.0.0.jar

    - name: List target directory
      run: ls -la target

    - name: Upload Release Asset (JAR)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        # Use the pattern for now, verify name with the ls output
        #asset_path: ./target/keycloak-auto-org-assigner-*.jar
        asset_path: /home/runner/work/keycloak-organization-assigner/keycloak-organization-assigner/target/keycloak-auto-org-assigner-*.jar
        asset_name: keycloak-auto-org-assigner-${{ github.event.release.tag_name }}.jar
        asset_content_type: application/java-archive